#apiVersion: v1
#kind: Service
#metadata:
#  name: postgres-public-service
#  labels:
#    app: postgres
#spec:
#  type: LoadBalancer
#  ports:
#    - port: 5432
#      targetPort: 5432
#      protocol: TCP
#  selector:
#    app: postgres
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
